version: '3.8'

services:
  postgres:
    build: ./postgresql/
    container_name: postgres_pet_expert
    image: library/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pet_expert

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app-service
    ports:
      - 8000:8000
    env_file:
      - .env
    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    restart: always